### ISSUE TITLE
Version 1.7.0 fails after first unsuccessful vote

### ISSUE THREAD

**Issue by Wasserfall159** [mattboy9921/SkipNight#34]
The title says it all - after upgrading from SkipNight 1.6.2 to 1.7.0, the plugin stops working after first unsuccessful vote. As long as the votes pass, the plugin behaves as expected, however first vote that does not pass results in two unwanted things:

1. No further votes can be processed. If any player tries to use /skipnight or /skipday, it just says something like "A vote just failed, you can't start another one now"
2. If any player disconnects after the first unsuccessful vote, the plugin throws an exception saying it could not pass PlayerQuitEvent to SkipNight v1.7.0. The example is attached below:

```
[12:32:39 INFO]: Honz_ lost connection: Disconnected
[12:32:39 ERROR]: Could not pass event PlayerQuitEvent to SkipNight v1.7.0
java.lang.NullPointerException: Cannot invoke "net.mattlabs.skipnight.util.VoteType.ordinal()" because "voteType" is null
        at net.mattlabs.skipnight.Vote.voteTypeStringCommand(Vote.java:431) ~[SkipNight-1.7.0.jar:?]
        at net.mattlabs.skipnight.Vote.onLogoff(Vote.java:68) ~[SkipNight-1.7.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor554.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-196]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:607) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:592) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2178) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2157) ~[?:?]
        at net.minecraft.network.Connection.handleDisconnection(Connection.java:818) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:254) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1586) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1393) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[12:32:40 INFO]: Honz_ left the game
```

My server software is Paper in its latest version for Minecraft 1.20.1.

Could you please take a look at it? Thank you in advance for fixing this issue.

**Comment by mattboy9921** [comment]
Hi  @Wasserfall159, I believe I've fixed this issue in one of the pre release builds. Please check out the releases page for those. I plan to release 1.8.0 once I have time to button it all up but for now, those releases should work.

**Comment by mattboy9921** [comment]
This should be fixed in the latest stable release.
