### ISSUE TITLE
Does not start on spigot 1.20.4

### ISSUE THREAD

**Issue by xiey0** [mattboy9921/SkipNight#36]
Full log: 
[16:34:15] [Server thread/INFO]: [SkipNight] Enabling SkipNight v1.8.0
[16:34:16] [Server thread/ERROR]: Error occurred while enabling SkipNight v1.8.0 (Is it up to date?)
net.mattlabs.skipnight.cloud.bukkit.BukkitCommandManager$BrigadierFailureException: Could not initialize Brigadier mappings. Reason: version too high ()
	at net.mattlabs.skipnight.cloud.bukkit.BukkitCommandManager.registerBrigadier(BukkitCommandManager.java:346) ~[?:?]
	at net.mattlabs.skipnight.cloud.paper.PaperCommandManager.registerBrigadier(PaperCommandManager.java:134) ~[?:?]
	at net.mattlabs.skipnight.SkipNight.onEnable(SkipNight.java:112) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:541) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4054-Spigot-e9ec548-619936d]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:455) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4054-Spigot-e9ec548-619936d]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:623) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4054-Spigot-e9ec548-619936d]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:409) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4054-Spigot-e9ec548-619936d]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4054-Spigot-e9ec548-619936d]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1000) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4054-Spigot-e9ec548-619936d]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4054-Spigot-e9ec548-619936d]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

and then after the server had started the command does not load.

**Comment by mattboy9921** [comment]
What version of Minecraft server are you running? Also is it Paper, Spigot, etc?

**Comment by xiey0** [comment]
> What version of Minecraft server are you running? Also is it Paper, Spigot, etc?

Spigot, 1.20.4.

**Comment by mattboy9921** [comment]
This issue seems to be related to Cloud which is also being tracked in #38. Please check there for updates regarding Cloud v2.
